version: '3'
services:
  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    restart: always

  inscricoes:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DBHOST=mongodb://database:3017
      - DBNAME=inscricoes_db
    restart: "no"